package com.mycompany.compraverymaven.vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;

public class Admin_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Menu
     */
    public Admin_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpContenedor = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnPedidosCliente = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnOfertas = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpContenedorLayout = new javax.swing.GroupLayout(jdpContenedor);
        jdpContenedor.setLayout(jdpContenedorLayout);
        jdpContenedorLayout.setHorizontalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        jdpContenedorLayout.setVerticalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setText("Perfil");
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 60));

        btnAlmacen.setText("Almacén");
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 108, 110, 60));

        btnProveedores.setText("Proveedores");
        jPanel1.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 60));

        btnCompras.setText("Compras");
        jPanel1.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, 60));

        btnPedidosCliente.setText("PedidosXcliente");
        jPanel1.add(btnPedidosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 60));

        btnVentas.setText("Ventas");
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, 56));

        btnOfertas.setText("Ofertas");
        jPanel1.add(btnOfertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 60));

        btnEmpleados.setText("Empleados");
        jPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 110, 60));

        btnProductos.setText("Productos");
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 220, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdpContenedor))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedor)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnAlmacen() {
        return btnAlmacen;
    }

    public JButton getBtnCompras() {
        return btnCompras;
    }

    public JButton getBtnEmpleados() {
        return btnEmpleados;
    }

    public JButton getBtnOfertas() {
        return btnOfertas;
    }

    public JButton getBtnPedidosCliente() {
        return btnPedidosCliente;
    }

    public JButton getBtnPerfil() {
        return btnPerfil;
    }

    public JButton getBtnProductos() {
        return btnProductos;
    }

    public JButton getBtnProveedores() {
        return btnProveedores;
    }

    public JButton getBtnVentas() {
        return btnVentas;
    }

    /**
     * @param args the command line arguments
     */
    public JDesktopPane getJdpContenedor() {
        return jdpContenedor;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnOfertas;
    private javax.swing.JButton btnPedidosCliente;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpContenedor;
    // End of variables declaration//GEN-END:variables
}
