package com.mycompany.compraverymaven.vista;

import javax.swing.JLabel;

public class Admin_Menu_Perfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin_Perfil
     */
    public Admin_Menu_Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        admin_image = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al MiniMarket <El Fast>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setText("Datos Completos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel3.setText("Direccion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel4.setText("Celular:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel5.setText("Cargo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel6.setText("DNI:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        lblDatos.setText("jLabel7");
        getContentPane().add(lblDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        lblDireccion.setText("jLabel8");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        lblCelular.setText("jLabel9");
        getContentPane().add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        lblCargo.setText("jLabel10");
        getContentPane().add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        lblDni.setText("jLabel11");
        getContentPane().add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        admin_image.setText("foto");
        getContentPane().add(admin_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getAdmin_image() {
        return admin_image;
    }

    public JLabel getLblCargo() {
        return lblCargo;
    }

    public JLabel getLblCelular() {
        return lblCelular;
    }

    public JLabel getLblDatos() {
        return lblDatos;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public JLabel getLblDni() {
        return lblDni;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    // End of variables declaration//GEN-END:variables
}
