/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.compraverymaven.vista;

import javax.swing.JLabel;

/**
 *
 * @author DAVID
 */
public class Almacenero_Menu_Perfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form Almacenero_Menu_Perfil
     */
    public Almacenero_Menu_Perfil() {
        initComponents();
    }

    public JLabel getLblDni() {
        return lblDni;
    }

    public JLabel getLblCargo() {
        return lblCargo;
    }

    public JLabel getLblCell() {
        return lblCell;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public JLabel getLblName() {
        return lblName;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        almacenero_image = new javax.swing.JLabel();
        lblNa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCell = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(430, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al MiniMarket <El Fast>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        almacenero_image.setText("foto");
        getContentPane().add(almacenero_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, 120));

        lblNa.setText("Nombre:");
        getContentPane().add(lblNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel3.setText("Direccion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel4.setText("Celular:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        getContentPane().add(lblCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 150, 20));
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 150, 20));
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, 20));

        jLabel6.setText("Cargo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        getContentPane().add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 150, 20));

        jLabel2.setText("Dni:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));
        getContentPane().add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel almacenero_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCell;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNa;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
