package com.mycompany.compraverymaven.vista;


import javax.swing.JButton;
import javax.swing.JDesktopPane;

/**
 *
 * @author DAVID
 */

public class Almacenero_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Almacenero_Menu
     */
    public Almacenero_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPerfil = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil.setText("PERFIL");
        btnPerfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 100));

        btnInventario.setText("INVENTARIO");
        btnInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, 100));

        btnClose.setText("CERRAR SESION");
        btnClose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 130, 110));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 0, 410));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 540, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDesktopPane getjDesktopPane1() {
        return jDesktopPane1;
    }

    /**
     * @param args the command line arguments
     */

    public JButton getBtnInventario() {
        return btnInventario;
    }

    public JButton getBtnPerfil() {
        return btnPerfil;
    }

    public JButton getBtnClose() {
        return btnClose;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
