/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.compraverymaven.vista;

/**
 *
 * @author DAVID
 */
public class Consumidor_DetalleProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consumidor_DetalleProducto
     */
    public Consumidor_DetalleProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_precio = new javax.swing.JLabel();
        jLabel_oferta = new javax.swing.JLabel();
        jcmb_cantidad = new javax.swing.JComboBox<>();
        btn_agregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxt_descripcion = new javax.swing.JTextPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_imagen.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_imagen.setOpaque(true);
        getContentPane().add(jLabel_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 150, 150));

        jLabel1.setText("Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel4.setText("Precio Oferta:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel2.setText("Descripción:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel_nombre.setText("jLabel6");
        getContentPane().add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel_precio.setText("jLabel8");
        getContentPane().add(jLabel_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel_oferta.setText("jLabel9");
        getContentPane().add(jLabel_oferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jcmb_cantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcmb_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        btn_agregar.setText("Añadir carrito");
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 280, -1));

        jScrollPane2.setViewportView(jtxt_descripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 180, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_imagen;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_oferta;
    private javax.swing.JLabel jLabel_precio;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcmb_cantidad;
    private javax.swing.JTextPane jtxt_descripcion;
    // End of variables declaration//GEN-END:variables
}
