/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.compraverymaven.vista;

/**
 *
 * @author DAVID
 */
public class Consumidor_BusquedaProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consumidor_BusquedaProducto
     */
    public Consumidor_BusquedaProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        imagen1 = new javax.swing.JLabel();
        txt_producto1 = new javax.swing.JLabel();
        txt_precio1 = new javax.swing.JLabel();
        txt_oferta1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTOS <EL FAST>");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 30, 300, -1));

        jTextField1.setText("buscar productos");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 560, -1));

        imagen1.setText("imagen");
        getContentPane().add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 80));

        txt_producto1.setText("nombre producto");
        getContentPane().add(txt_producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txt_precio1.setText("precio producto");
        getContentPane().add(txt_precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txt_oferta1.setText("oferta producto");
        getContentPane().add(txt_oferta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel txt_oferta1;
    private javax.swing.JLabel txt_precio1;
    private javax.swing.JLabel txt_producto1;
    // End of variables declaration//GEN-END:variables
}
